#'hist_ST_LFV_TCMuTau_Scalar.root':
#  type: signal
#  pretty-name: 'LFVSTcs'
#  cross-section: 0.00740
#  generated-events: 4822000.0
#  group: GLFVSTcs
#  order: 1

'hist_ST_LFV_TCMuTau_Vector.root':
  type: signal
  pretty-name: 'LFVSTcv'
  cross-section: 0.0368
  generated-events: 4856000.0
  group: GLFVSTcv
  order: 1

#'hist_ST_LFV_TCMuTau_Tensor.root':
#  type: signal
#  pretty-name: 'LFVSTct'
#  cross-section: 0.1784
#  generated-events: 3404000.0
#  group: GLFVSTct
#  order: 1
#
#'hist_ST_LFV_TUMuTau_Scalar.root':
#  type: signal
#  pretty-name: 'LFVSTus'
#  cross-section: 0.0838
#  generated-events: 4807000.0
#  group: GLFVSTus
#  order: 1

'hist_ST_LFV_TUMuTau_Vector.root':
  type: signal
  pretty-name: 'LFVSTuv'
  cross-section: 0.393
  generated-events: 4897981.0
  group: GLFVSTuv
  order: 2

#'hist_ST_LFV_TUMuTau_Tensor.root':
#  type: signal
#  pretty-name: 'LFVSTut'
#  cross-section: 1.796
#  generated-events: 3478000.0
#  group: GLFVSTut
#  order: 1
#
#'hist_TT_LFV_TToCMuTau_Scalar.root':
#  type: signal
#  pretty-name: 'LFVTTcs'
#  cross-section: 0.00269
#  generated-events: 3478000.0 
#  group: GLFVTTcs
#  order: 1

'hist_TT_LFV_TToCMuTau_Vector.root':
  type: signal
  pretty-name: 'LFVTTcv'
  cross-section: 0.0215
  generated-events: 3370000.0
  group: GLFVTTcv
  order: 3

#'hist_TT_LFV_TToCMuTau_Tensor.root':
#  type: signal
#  pretty-name: 'LFVTTct'
#  cross-section: 0.1290
#  generated-events: 3448000.0
#  group: GLFVTTct
#  order: 1
#
#'hist_TT_LFV_TToUMuTau_Scalar.root':
#  type: signal
#  pretty-name: 'LFVTTus'
#  cross-section: 0.00269
#  generated-events: 4804000.0
#  group: GLFVTTus
#  order: 1

'hist_TT_LFV_TToUMuTau_Vector.root':
  type: signal
  pretty-name: 'LFVTTuv'
  cross-section: 0.0215
  generated-events: 4842000.0
  group: GLFVTTuv
  order: 4

#'hist_TT_LFV_TToUMuTau_Tensor.root':
#  type: signal
#  pretty-name: 'LFVTTut'
#  cross-section: 0.1290
#  generated-events: 4716000.0
#  group: GLFVTTut
#  order: 1

# DATA
'hist_Run18.root':
  type: data
  pretty-name: 'Data'
  group: GData

# Backgrounds
'hist_TTToSemiLeptonic.root':
  type: mc
  pretty-name: 'TTToSemiLeptonic'
  cross-section: 365.34
  generated-events: 486770000.0
  group: Gttsemi
  yields-group: '2\ttbar LJ'
  order: 6

'hist_TTTo2L2Nu.root':
  type: mc
  pretty-name: 'TTTo2L2Nu'
  cross-section: 88.29
  generated-events: 148470000.0
  group: Gttdi
  yields-group: '2\ttbar LL'
  order: 7

'hist_TTToHadronic.root':
  type: mc
  pretty-name: 'TTToHadronic'
  cross-section: 377.96
  generated-events: 340002000.0
  group: Gtthad
  yields-group: '2\ttbar Had'
  order: 8

'hist_TTWJetsToLNu.root':
  type: mc
  pretty-name: 'TTWJetsToLNu'
  cross-section: 0.2043
  generated-events: 10522657.0
  group: GttV
  yields-group: '4Other'
  order: 11

'hist_TTWJetsToQQ.root':
  type: mc
  pretty-name: 'TTWJetsToQQ'
  cross-section: 0.4062
  generated-events: 970179.0
  group: GttV
  yields-group: '4Other'
  order: 12

'hist_TTZToLLNuNu.root':
  type: mc
  pretty-name: 'TTZToLLNuNu'
  cross-section: 0.2529
  generated-events: 19992000.0
  group: GttV
  yields-group: '4Other'
  order: 13

'hist_TTZToQQ.root':
  type: mc
  pretty-name: 'TTZToQQ'
  cross-section: 0.5297
  generated-events: 19960000.0
  group: GttV
  yields-group: '4Other'
  order: 14

'hist_ST_t-channel_top.root':
  type: mc
  pretty-name: 'SingleTopt'
  cross-section: 136.02
  generated-events: 176473000.0
  group: GSingleT
  yields-group: '4Other'
  order: 16

'hist_ST_t-channel_antitop.root':
  type: mc
  pretty-name: 'SingleTbart'
  cross-section: 80.95
  generated-events: 94864000.0
  group: GSingleT
  yields-group: '4Other'
  order: 17

'hist_ST_tW_top.root':
  type: mc
  pretty-name: 'SingleToptW'
  cross-section: 35.85
  generated-events: 5979000.0
  group: GSingleT
  yields-group: '4Other'
  order: 18

'hist_ST_tW_antitop.root':
  type: mc
  pretty-name: 'SingleTbartW'
  cross-section: 35.85
  generated-events: 5780000.0
  group: GSingleT
  yields-group: '4Other'
  order: 19

'hist_WW.root':
  type: mc
  pretty-name: 'WW'
  cross-section: 118.7
  generated-events: 15670000.0
  group: GVV
  yields-group: '4Other'
  order: 20

'hist_WZ.root':
  type: mc
  pretty-name: 'WZ'
  cross-section: 47.13
  generated-events: 7986000.0
  group: GVV
  yields-group: '4Other'
  order: 21

'hist_ZZ.root':
  type: mc
  pretty-name: 'ZZ'
  cross-section: 16.523
  generated-events: 3907000.0
  group: GVV
  yields-group: '4Other'
  order: 22

'hist_DYJetsToLL_M-10to50.root':
  type: mc
  pretty-name: 'DYJets10to50'
  cross-section: 18610
  generated-events: 99449093
  group: GZJets
  yields-group: '4Other'
  order: 23

'hist_DYJetsToLL_M-50_amcatnlo.root':
  type: mc
  pretty-name: 'DYJets'
  cross-section: 6077.22
  generated-events: 196039620.0
  group: GZJets
  yields-group: '4Other'
  order: 24

'hist_WJetsToLNu_HT-0To100.root':
  type: mc
  pretty-name: 'WJetsToLNu_HT-0To100'
  cross-section: 59373.3
  generated-events: 79688979 # total * 0.96 (htcut)
  group: GWJets
  yields-group: '4Other'
  order: 25

'hist_WJetsToLNu_HT-100To200.root':
  type: mc
  pretty-name: 'WJetsToLNu_HT-100To200'
  cross-section: 1335.585
  generated-events: 66195407.0
  group: GWJets
  yields-group: '4Other'
  order: 26

'hist_WJetsToLNu_HT-200To400.root':
  type: mc
  pretty-name: 'WJetsToLNu_HT-200To400'
  cross-section: 360.4194
  generated-events: 56898682.0
  group: GWJets
  yields-group: '4Other'
  order: 27

'hist_WJetsToLNu_HT-400To600.root':
  type: mc
  pretty-name: 'WJetsToLNu_HT-400To600'
  cross-section: 49.35019
  generated-events: 7545618.0
  group: GWJets
  yields-group: '4Other'
  order: 28

'hist_WJetsToLNu_HT-600To800.root':
  type: mc
  pretty-name: 'WJetsToLNu_HT-600To800'
  cross-section: 13.4960
  generated-events: 7556181.0
  group: GWJets
  yields-group: '4Other'
  order: 29

'hist_WJetsToLNu_HT-800To1200.root':
  type: mc
  pretty-name: 'WJetsToLNu_HT-800To1200'
  cross-section: 6.612202
  generated-events: 7418726.0
  group: GWJets
  yields-group: '4Other'
  order: 30

'hist_WJetsToLNu_HT-1200To2500.root':
  type: mc
  pretty-name: 'WJetsToLNu_HT-1200To2500'
  cross-section: 1.770228
  generated-events: 6855219.0
  group: GWJets
  yields-group: '4Other'
  order: 31

'hist_WJetsToLNu_HT-2500ToInf.root':
  type: mc
  pretty-name: 'WJetsToLNu_HT-2500ToInf'
  cross-section: 0.135072
  generated-events: 2097648.0
  group: GWJets
  yields-group: '4Other'
  order: 32

'hist_QCD_Pt-15To20.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 3819570.0
  generated-events: 9230748.0
  group: GQCD
  yields-group: '5QCD'
  order: 33

'hist_QCD_Pt-20To30.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 2960198.4
  generated-events: 60662268.0
  group: GQCD
  yields-group: '5QCD'
  order: 34

'hist_QCD_Pt-30To50.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 1652471.5
  generated-events: 58236193.0
  group: GQCD
  yields-group: '5QCD'
  order: 35

'hist_QCD_Pt-50To80.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 437504.1
  generated-events: 39479014.0
  group: GQCD
  yields-group: '5QCD'
  order: 36

'hist_QCD_Pt-80To120.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 106033.7
  generated-events: 45269532.0
  group: GQCD
  yields-group: '5QCD'
  order: 37

'hist_QCD_Pt-120To170.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 25190.5
  generated-events: 39359230.0
  group: GQCD
  yields-group: '5QCD'
  order: 38

'hist_QCD_Pt-170To300.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 8654.5
  generated-events: 72031492.0
  group: GQCD
  yields-group: '5QCD'
  order: 39

'hist_QCD_Pt-300To470.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 797.4
  generated-events: 58771417.0
  group: GQCD
  yields-group: '5QCD'
  order: 40

'hist_QCD_Pt-470To600.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 79.0
  generated-events: 38645779.0
  group: GQCD
  yields-group: '5QCD'
  order: 41

'hist_QCD_Pt-600To800.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 25.1
  generated-events: 38477713.0
  group: GQCD
  yields-group: '5QCD'
  order: 42

'hist_QCD_Pt-800To1000.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 4.7
  generated-events: 78922680.0
  group: GQCD
  yields-group: '5QCD'
  order: 43

'hist_QCD_Pt-1000.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 1.6
  generated-events: 27427195.0
  group: GQCD
  yields-group: '5QCD'
  order: 44

#'hist_ttHTobb.root':
#  type: mc
#  pretty-name: 'ttHTobb'
#  cross-section: 0.2934
#  generated-events: 11590377
#  group: GttV
#  yields-group: '4Other'
#  order: 9
#
#'hist_ttHToNonbb.root':
#  type: mc
#  pretty-name: 'ttHToNonbb'
#  cross-section: 0.2151
#  generated-events: 7368333
#  group: GttV
#  yields-group: '4Other'
#  order: 10
#
#'hist_SingleTops.root':
#  type: mc
#  pretty-name: 'SingleTops'
#  cross-section: 3.36
#  generated-events: 12447484
#  group: GSingleT
#  yields-group: '4Other'
#  order: 15
