#'ST_LFV_TCMuTau_Scalar_18_norm.root':
#  type: signal
#  pretty-name: 'LFVSTcs'
#  cross-section: 0.00740
#  generated-events: 4822000.0
#  group: GLFVSTcs
#  order: 1

'ST_LFV_TCMuTau_Vector_18_norm.root':
  type: signal
  pretty-name: 'LFVSTcv'
  cross-section: 0.0368
  generated-events: 4856000.0
  group: GLFVSTcv
  order: 1

#'ST_LFV_TCMuTau_Tensor_18_norm.root':
#  type: signal
#  pretty-name: 'LFVSTct'
#  cross-section: 0.1784
#  generated-events: 3404000.0
#  group: GLFVSTct
#  order: 1
#
#'ST_LFV_TUMuTau_Scalar_18_norm.root':
#  type: signal
#  pretty-name: 'LFVSTus'
#  cross-section: 0.0838
#  generated-events: 4807000.0
#  group: GLFVSTus
#  order: 1

'ST_LFV_TUMuTau_Vector_18_norm.root':
  type: signal
  pretty-name: 'LFVSTuv'
  cross-section: 0.393
  generated-events: 4897981.0
  group: GLFVSTuv
  order: 2

#'ST_LFV_TUMuTau_Tensor_18_norm.root':
#  type: signal
#  pretty-name: 'LFVSTut'
#  cross-section: 1.796
#  generated-events: 3478000.0
#  group: GLFVSTut
#  order: 1
#
#'TT_LFV_TToCMuTau_Scalar_18_norm.root':
#  type: signal
#  pretty-name: 'LFVTTcs'
#  cross-section: 0.00269
#  generated-events: 3478000.0 
#  group: GLFVTTcs
#  order: 1

'TT_LFV_TToCMuTau_Vector_18_norm.root':
  type: signal
  pretty-name: 'LFVTTcv'
  cross-section: 0.0215
  generated-events: 3370000.0
  group: GLFVTTcv
  order: 3

#'TT_LFV_TToCMuTau_Tensor_18_norm.root':
#  type: signal
#  pretty-name: 'LFVTTct'
#  cross-section: 0.1290
#  generated-events: 3448000.0
#  group: GLFVTTct
#  order: 1
#
#'TT_LFV_TToUMuTau_Scalar_18_norm.root':
#  type: signal
#  pretty-name: 'LFVTTus'
#  cross-section: 0.00269
#  generated-events: 4804000.0
#  group: GLFVTTus
#  order: 1

'TT_LFV_TToUMuTau_Vector_18_norm.root':
  type: signal
  pretty-name: 'LFVTTuv'
  cross-section: 0.0215
  generated-events: 4842000.0
  group: GLFVTTuv
  order: 4

#'TT_LFV_TToUMuTau_Tensor_18_norm.root':
#  type: signal
#  pretty-name: 'LFVTTut'
#  cross-section: 0.1290
#  generated-events: 4716000.0
#  group: GLFVTTut
#  order: 1

# DATA
'Run18_norm.root':
  type: data
  pretty-name: 'Data'
  group: GData

# Backgrounds
'TTToSemiLeptonic_18_norm.root':
  type: mc
  pretty-name: 'TTToSemiLeptonic'
  cross-section: 365.34
  generated-events: 486770000.0
  group: Gttsemi
  yields-group: '2\ttbar LF'
  order: 6

'TTTo2L2Nu_18_norm.root':
  type: mc
  pretty-name: 'TTTo2L2Nu'
  cross-section: 88.29
  generated-events: 148470000.0
  group: Gttdi
  yields-group: '2\ttbar LF'
  order: 7

'TTToHadronic_18_norm.root':
  type: mc
  pretty-name: 'TTToHadronic'
  cross-section: 377.96
  generated-events: 340002000.0
  group: Gtthad
  yields-group: '2\ttbar LF'
  order: 8

'TTWJetsToLNu_18_norm.root':
  type: mc
  pretty-name: 'TTWJetsToLNu'
  cross-section: 0.2043
  generated-events: 10522657.0
  group: GttV
  yields-group: '3Other'
  order: 11

'TTWJetsToQQ_18_norm.root':
  type: mc
  pretty-name: 'TTWJetsToQQ'
  cross-section: 0.4062
  generated-events: 970179.0
  group: GttV
  yields-group: '3Other'
  order: 12

'TTZToLLNuNu_18_norm.root':
  type: mc
  pretty-name: 'TTZToLLNuNu'
  cross-section: 0.2529
  generated-events: 19992000.0
  group: GttV
  yields-group: '3Other'
  order: 13

'TTZToQQ_18_norm.root':
  type: mc
  pretty-name: 'TTZToQQ'
  cross-section: 0.5297
  generated-events: 19960000.0
  group: GttV
  yields-group: '3Other'
  order: 14

'ST_t-channel_top_18_norm.root':
  type: mc
  pretty-name: 'SingleTopt'
  cross-section: 136.02
  generated-events: 176473000.0
  group: GSingleT
  yields-group: '3Other'
  order: 16

'ST_t-channel_antitop_18_norm.root':
  type: mc
  pretty-name: 'SingleTbart'
  cross-section: 80.95
  generated-events: 94864000.0
  group: GSingleT
  yields-group: '3Other'
  order: 17

'ST_tW_top_18_norm.root':
  type: mc
  pretty-name: 'SingleToptW'
  cross-section: 35.85
  generated-events: 5979000.0
  group: GSingleT
  yields-group: '3Other'
  order: 18

'ST_tW_antitop_18_norm.root':
  type: mc
  pretty-name: 'SingleTbartW'
  cross-section: 35.85
  generated-events: 5780000.0
  group: GSingleT
  yields-group: '3Other'
  order: 19

'WW_18_norm.root':
  type: mc
  pretty-name: 'WW'
  cross-section: 118.7
  generated-events: 15670000.0
  group: GVV
  yields-group: '3Other'
  order: 20

'WZ_18_norm.root':
  type: mc
  pretty-name: 'WZ'
  cross-section: 47.13
  generated-events: 7986000.0
  group: GVV
  yields-group: '3Other'
  order: 21

'ZZ_18_norm.root':
  type: mc
  pretty-name: 'ZZ'
  cross-section: 16.523
  generated-events: 3907000.0
  group: GVV
  yields-group: '3Other'
  order: 22

'DYJetsToLL_M-10to50_18_norm.root':
  type: mc
  pretty-name: 'DYJets10to50'
  cross-section: 18610
  generated-events: 99449093
  group: GZJets
  yields-group: '3Other'
  order: 23

'DYJetsToLL_M-50_amcatnlo_18_norm.root':
  type: mc
  pretty-name: 'DYJets'
  cross-section: 6225.42
  generated-events: 196039620.0
  group: GZJets
  yields-group: '3Other'
  order: 24

'WJetsToLNu_HT-0To100_18_norm.root':
  type: mc
  pretty-name: 'WJetsToLNu_HT-0To100'
  cross-section: 59373.3
  generated-events: 79688979 # total * 0.96 (htcut)
  group: GWJets
  yields-group: '3Other'
  order: 25

'WJetsToLNu_HT-100To200_18_norm.root':
  type: mc
  pretty-name: 'WJetsToLNu_HT-100To200'
  cross-section: 1335.585
  generated-events: 66195407.0
  group: GWJets
  yields-group: '3Other'
  order: 26

'WJetsToLNu_HT-200To400_18_norm.root':
  type: mc
  pretty-name: 'WJetsToLNu_HT-200To400'
  cross-section: 360.4194
  generated-events: 56898682.0
  group: GWJets
  yields-group: '3Other'
  order: 27

'WJetsToLNu_HT-400To600_18_norm.root':
  type: mc
  pretty-name: 'WJetsToLNu_HT-400To600'
  cross-section: 49.35019
  generated-events: 7545618.0
  group: GWJets
  yields-group: '3Other'
  order: 28

'WJetsToLNu_HT-600To800_18_norm.root':
  type: mc
  pretty-name: 'WJetsToLNu_HT-600To800'
  cross-section: 13.4960
  generated-events: 7556181.0
  group: GWJets
  yields-group: '3Other'
  order: 29

'WJetsToLNu_HT-800To1200_18_norm.root':
  type: mc
  pretty-name: 'WJetsToLNu_HT-800To1200'
  cross-section: 6.612202
  generated-events: 7418726.0
  group: GWJets
  yields-group: '3Other'
  order: 30

'WJetsToLNu_HT-1200To2500_18_norm.root':
  type: mc
  pretty-name: 'WJetsToLNu_HT-1200To2500'
  cross-section: 1.770228
  generated-events: 6855219.0
  group: GWJets
  yields-group: '3Other'
  order: 31

'WJetsToLNu_HT-2500ToInf_18_norm.root':
  type: mc
  pretty-name: 'WJetsToLNu_HT-2500ToInf'
  cross-section: 0.135072
  generated-events: 2097648.0
  group: GWJets
  yields-group: '3Other'
  order: 32

'QCD_Pt-15To20_18_norm.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 3819570.0
  generated-events: 9230748.0
  group: GQCD
  yields-group: '4QCD'
  order: 33

'QCD_Pt-20To30_18_norm.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 2960198.4
  generated-events: 60662268.0
  group: GQCD
  yields-group: '4QCD'
  order: 34

'QCD_Pt-30To50_18_norm.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 1652471.5
  generated-events: 58236193.0
  group: GQCD
  yields-group: '4QCD'
  order: 35

'QCD_Pt-50To80_18_norm.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 437504.1
  generated-events: 39479014.0
  group: GQCD
  yields-group: '4QCD'
  order: 36

'QCD_Pt-80To120_18_norm.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 106033.7
  generated-events: 45269532.0
  group: GQCD
  yields-group: '4QCD'
  order: 37

'QCD_Pt-120To170_18_norm.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 25190.5
  generated-events: 39359230.0
  group: GQCD
  yields-group: '4QCD'
  order: 38

'QCD_Pt-170To300_18_norm.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 8654.5
  generated-events: 72031492.0
  group: GQCD
  yields-group: '4QCD'
  order: 39

'QCD_Pt-300To470_18_norm.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 797.4
  generated-events: 58771417.0
  group: GQCD
  yields-group: '4QCD'
  order: 40

'QCD_Pt-470To600_18_norm.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 79.0
  generated-events: 38645779.0
  group: GQCD
  yields-group: '4QCD'
  order: 41

'QCD_Pt-600To800_18_norm.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 25.1
  generated-events: 38477713.0
  group: GQCD
  yields-group: '4QCD'
  order: 42

'QCD_Pt-800To1000_18_norm.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 4.7
  generated-events: 78922680.0
  group: GQCD
  yields-group: '4QCD'
  order: 43

'QCD_Pt-1000_18_norm.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 1.6
  generated-events: 27427195.0
  group: GQCD
  yields-group: '4QCD'
  order: 44

#'hist_ttHTobb.root':
#  type: mc
#  pretty-name: 'ttHTobb'
#  cross-section: 0.2934
#  generated-events: 11590377
#  group: GttV
#  yields-group: '3Other'
#  order: 9
#
#'hist_ttHToNonbb.root':
#  type: mc
#  pretty-name: 'ttHToNonbb'
#  cross-section: 0.2151
#  generated-events: 7368333
#  group: GttV
#  yields-group: '3Other'
#  order: 10
#
#'hist_SingleTops.root':
#  type: mc
#  pretty-name: 'SingleTops'
#  cross-section: 3.36
#  generated-events: 12447484
#  group: GSingleT
#  yields-group: '3Other'
#  order: 15



