#'hist_ST_LFV_TCMuTau_Scalar.root':
#  type: signal
#  pretty-name: 'LFVSTcs'
#  cross-section: 0.00740
#  generated-events: 1580000.0
#  group: GLFVSTcs
#  order: 1

'hist_ST_LFV_TCMuTau_Vector.root':
  type: signal
  pretty-name: 'LFVSTcv'
  cross-section: 0.0368
  generated-events: 1579000.0
  group: GLFVSTcv
  order: 1

#'hist_ST_LFV_TCMuTau_Tensor.root':
#  type: signal
#  pretty-name: 'LFVSTct'
#  cross-section: 0.1784
#  generated-events: 1578000.0
#  group: GLFVSTct
#  order: 1
#
#'hist_ST_LFV_TUMuTau_Scalar.root':
#  type: signal
#  pretty-name: 'LFVSTus'
#  cross-section: 0.0838
#  generated-events: 1578000.0
#  group: GLFVSTus
#  order: 1

'hist_ST_LFV_TUMuTau_Vector.root':
  type: signal
  pretty-name: 'LFVSTuv'
  cross-section: 0.393
  generated-events: 1580000.0
  group: GLFVSTuv
  order: 2

#'hist_ST_LFV_TUMuTau_Tensor.root':
#  type: signal
#  pretty-name: 'LFVSTut'
#  cross-section: 1.796
#  generated-events: 1580000.0
#  group: GLFVSTut
#  order: 1
#
#'hist_TT_LFV_TCMuTau_Scalar.root':
#  type: signal
#  pretty-name: 'LFVTTcs'
#  cross-section: 0.00269
#  generated-events: 1580000.0
#  group: GLFVTTcs
#  order: 1

'hist_TT_LFV_TCMuTau_Vector.root':
  type: signal
  pretty-name: 'LFVTTcv'
  cross-section: 0.0215
  generated-events: 1577000.0
  group: GLFVTTcv
  order: 3

#'hist_TT_LFV_TCMuTau_Tensor.root':
#  type: signal
#  pretty-name: 'LFVTTct'
#  cross-section: 0.1290
#  generated-events: 1580000.0
#  group: GLFVTTct
#  order: 1
#
#'hist_TT_LFV_TUMuTau_Scalar.root':
#  type: signal
#  pretty-name: 'LFVTTus'
#  cross-section: 0.00269
#  generated-events: 1580000.0
#  group: GLFVTTus
#  order: 1

'hist_TT_LFV_TUMuTau_Vector.root':
  type: signal
  pretty-name: 'LFVTTuv'
  cross-section: 0.0215
  generated-events: 1580000.0
  group: GLFVTTuv
  order: 4

#'hist_TT_LFV_TUMuTau_Tensor.root':
#  type: signal
#  pretty-name: 'LFVTTut'
#  cross-section: 0.1290
#  generated-events: 1580000.0
#  group: GLFVTTut
#  order: 1

'hist_SingleMuon2016post.root':
  type: data
  pretty-name: 'Data'
  group: GData

'hist_TTToSemiLeptonic.root':
  type: mc
  pretty-name: 'TTToSemiLeptonic'
  cross-section: 365.34
  generated-events: 157314692.0
  group: Gttlj
  yields-group: '2\ttbar LJ'
  order: 6

'hist_TTTo2L2Nu.root':
  type: mc
  pretty-name: 'TTTo2L2Nu'
  cross-section: 88.29
  generated-events: 47092114.0
  group: Gttll
  yields-group: '1\ttbar LL'
  order: 7

'hist_TTToHadronic.root':
  type: mc
  pretty-name: 'TTToHadronic'
  cross-section: 377.96
  generated-events: 111680750.0
  group: Gttjj
  yields-group: '3\ttbar Had'
  order: 8

#'hist_ttHJetTobb.root':
#  type: mc
#  pretty-name: 'ttHTobb'
#  cross-section: 0.5023
#  generated-events: #FIXME
#  group: GttV
#  yields-group: '7tt+X'
#  order: 9
#
#'hist_ttHJetToNonbb.root':
#  type: mc
#  pretty-name: 'ttHToNonbb'
#  cross-section: 0.5066
#  generated-events: #FIXME
#  group: GttV
#  yields-group: '7tt+X'
#  order: 10

'hist_TTWJetsToLNu.root':
  type: mc
  pretty-name: 'TTWJetsToLNu'
  cross-section: 0.2043
  generated-events: 400706.0
  group: GttV
  yields-group: '7tt+X'
  order: 11

'hist_TTWJetsToQQ.root':
  type: mc
  pretty-name: 'TTWJetsToQQ'
  cross-section: 0.4062
  generated-events: 168951.0
  group: GttV
  yields-group: '7tt+X'
  order: 12

'hist_TTZToLLNuNu.root':
  type: mc
  pretty-name: 'TTZToLLNuNu'
  cross-section: 0.2529
  generated-events: 3058448.0
  group: GttV
  yields-group: '7tt+X'
  order: 13

'hist_TTZToQQ.root':
  type: mc
  pretty-name: 'TTZToQQ'
  cross-section: 0.5297
  generated-events: 2879374.0
  group: GttV
  yields-group: '7tt+X'
  order: 14

'hist_ST_s_4f_lepton.root':
  type: mc
  pretty-name: 'SingleTops'
  cross-section: 3.36
  generated-events: 4085988.0
  group: GSingleT
  yields-group: '5Single Top'
  order: 15

'hist_ST_t_top_4f.root':
  type: mc
  pretty-name: 'SingleTopt'
  cross-section: 136.02
  generated-events: 58866028.0
  group: GSingleT
  yields-group: '5Single Top'
  order: 16

'hist_ST_t_antitop_4f.root':
  type: mc
  pretty-name: 'SingleTbart'
  cross-section: 80.95
  generated-events: 28677096.0
  group: GSingleT
  yields-group: '5Single Top'
  order: 17

'hist_ST_tW_top_5f.root':
  type: mc
  pretty-name: 'SingleToptW'
  cross-section: 35.85
  generated-events: 2433862.0
  group: GSingleT
  yields-group: '5Single Top'
  order: 18

'hist_ST_tW_antitop_5f.root':
  type: mc
  pretty-name: 'SingleTbartW'
  cross-section: 35.85
  generated-events: 2523884.0
  group: GSingleT
  yields-group: '5Single Top'
  order: 19

'hist_WW.root':
  type: mc
  pretty-name: 'WW'
  cross-section: 118.7
  generated-events: 15907000.0
  group: GVV
  yields-group: '8VV'
  order: 20

'hist_WZ.root':
  type: mc
  pretty-name: 'WZ'
  cross-section: 47.13
  generated-events: 7768000.0
  group: GVV
  yields-group: '8VV'
  order: 21

'hist_ZZ.root':
  type: mc
  pretty-name: 'ZZ'
  cross-section: 16.523
  generated-events: 1114000.0
  group: GVV
  yields-group: '8VV'
  order: 22

'hist_DYJetsToLL_M10to50.root':
  type: mc
  pretty-name: 'DYJets10to50'
  cross-section: 18610
  generated-events: 26927726.0
  group: GZJets
  yields-group: '4Z+Jets'
  order: 23

'hist_DYJetsToLL_M50_amc.root':
  type: mc
  pretty-name: 'DYJets'
  cross-section: 6077.22
  generated-events: 64079563.0
  group: GZJets
  yields-group: '4Z+Jets'
  order: 24

'hist_WJetsToLNu_HT0To100.root':
  type: mc
  pretty-name: 'WJetsToLNu_HT0To100'
  cross-section: 59373.3
  generated-events: 85986988.0 # total 88463979.0 * 0.972
  group: GWJets
  yields-group: '6W+Jets'
  order: 25

'hist_WJetsToLNu_HT100To200.root':
  type: mc
  pretty-name: 'WJetsToLNu_HT100To200'
  cross-section: 1335.585
  generated-events: 19616492.0
  group: GWJets
  yields-group: '6W+Jets'
  order: 26

'hist_WJetsToLNu_HT200To400.root':
  type: mc
  pretty-name: 'WJetsToLNu_HT200To400'
  cross-section: 360.4194
  generated-events: 16584072.0
  group: GWJets
  yields-group: '6W+Jets'
  order: 27

'hist_WJetsToLNu_HT400To600.root':
  type: mc
  pretty-name: 'WJetsToLNu_HT400To600'
  cross-section: 49.35019
  generated-events: 2237687.0
  group: GWJets
  yields-group: '6W+Jets'
  order: 28

'hist_WJetsToLNu_HT600To800.root':
  type: mc
  pretty-name: 'WJetsToLNu_HT600To800'
  cross-section: 13.4960
  generated-events: 2205351.0
  group: GWJets
  yields-group: '6W+Jets'
  order: 29

'hist_WJetsToLNu_HT800To1200.root':
  type: mc
  pretty-name: 'WJetsToLNu_HT800To1200'
  cross-section: 6.612202
  generated-events: 2190406.0
  group: GWJets
  yields-group: '6W+Jets'
  order: 30

'hist_WJetsToLNu_HT1200To2500.root':
  type: mc
  pretty-name: 'WJetsToLNu_HT1200To2500'
  cross-section: 1.770228
  generated-events: 2090561.0
  group: GWJets
  yields-group: '6W+Jets'
  order: 31

'hist_WJetsToLNu_HT2500ToInf.root':
  type: mc
  pretty-name: 'WJetsToLNu_HT2500ToInf'
  cross-section: 0.135072
  generated-events: 677141.0
  group: GWJets
  yields-group: '6W+Jets'
  order: 32

#'hist_QCD_Pt15To20_MuEnriched.root':
#  type: mc
#  pretty-name: 'QCD'
#  cross-section: 
#  generated-events:
#  group: GQCD
#  yields-group: '9QCD'
#  order: 33

'hist_QCD_Pt20To30_MuEnriched.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 2960198.4
  generated-events: 30255176.0
  group: GQCD
  yields-group: '9QCD'
  order: 34

'hist_QCD_Pt30To50_MuEnriched.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 1652471.5
  generated-events: 35397812.0
  group: GQCD
  yields-group: '9QCD'
  order: 35

'hist_QCD_Pt50To80_MuEnriched.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 437504.1
  generated-events: 22279218.0
  group: GQCD
  yields-group: '9QCD'
  order: 36

'hist_QCD_Pt80To120_MuEnriched.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 106033.7
  generated-events: 23407998.0
  group: GQCD
  yields-group: '9QCD'
  order: 37

'hist_QCD_Pt120To170_MuEnriched.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 25190.5
  generated-events: 19763172.0
  group: GQCD
  yields-group: '9QCD'
  order: 38

'hist_QCD_Pt170To300_MuEnriched.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 8654.5
  generated-events: 36800197.0
  group: GQCD
  yields-group: '9QCD'
  order: 39

'hist_QCD_Pt300To470_MuEnriched.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 797.4
  generated-events: 30061697.0
  group: GQCD
  yields-group: '9QCD'
  order: 40

'hist_QCD_Pt470To600_MuEnriched.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 79.0
  generated-events: 20185257.0
  group: GQCD
  yields-group: '9QCD'
  order: 41

'hist_QCD_Pt600To800_MuEnriched.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 25.1
  generated-events: 19553333.0
  group: GQCD
  yields-group: '9QCD'
  order: 42

'hist_QCD_Pt800To1000_MuEnriched.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 4.7
  generated-events: 41592873.0
  group: GQCD
  yields-group: '9QCD'
  order: 43

'hist_QCD_Pt1000_MuEnriched.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 1.6
  generated-events: 14243204.0
  group: GQCD
  yields-group: '9QCD'
  order: 44
