GData:
  legend: 'Data'
  marker-size: 0.6

Gttdi:
  fill-color: '#330000'
  legend: 'TT-di'

Gttsemi:
  fill-color: '#990000'
  legend: 'TT-semi'

Gtthad:
  fill-color: '#cc0000'
  legend: 'tthad'

GttV:
  fill-color: '#ff66ff'
  legend: 'ttV/H'

GZJets:
  fill-color: '#000099'
  legend: 'ZJets'

GWJets:
  fill-color: '#ff9933'
  legend: 'WJets'

GSingleT:
  fill-color: '#990099'
  legend: 'ST'

GVV:
  fill-color: '#00cccc'
  legend: 'VV'

GQCD:
  fill-color: '#d0cfd4'
  legend: 'QCD'

#GLFVSTcs:
#  line-color: '#d0cfd4'
#  legend: 'STLFVc_s'

GLFVSTcv:
  line-color: '#99CC66'
  legend: 'STLFVc_v'

#GLFVSTct:
#  line-color: '#d0cfd4'
#  legend: 'STLFVc_t'
#
#GLFVSTus:
#  line-color: '#d0cfd4'
#  legend: 'STLFVu_s'

GLFVSTuv:
  line-color: '#6B8551'
  legend: 'STLFVu_v'

#GLFVSTut:
#  line-color: '#d0cfd4'
#  legend: 'STLFVu_t'
#
#GLFVTTcs:
#  line-color: '#d0cfd4'
#  legend: 'TTLFVc_s'

GLFVTTcv:
  line-color: '#908DCC'
  legend: 'TTLFVc_v'

#GLFVTTct:
#  line-color: '#d0cfd4'
#  legend: 'TTLFVc_t'
#
#GLFVTTus:
#  line-color: '#d0cfd4'
#  legend: 'TTLFVu_s'

GLFVTTuv:
  line-color: '#4F4D80'
  legend: 'TTLFVu_v'

#GLFVTTut:
#  line-color: '#d0cfd4'
#  legend: 'TTLFVu_t'

#GSTHct:
#  line-color: '#006666'
#  legend: 'STHct'
#
#GSTHut:
#  line-color: '#666600'
#  legend: 'STHut'
#
#GTTHct:
#  line-color: '#0000cc'
#  legend: 'TTHct'
#
#GTTHut:
#  line-color: '#cccc00'
#  legend: 'TTHut'
