#jet multiplicities
'h_ncleanjetspass_notausf_S1':
  log-y: true 
  sort-by-yields: true 
  save-extensions: ['pdf']

'h_ncleanjetspass_S2':
  log-y: true 
  sort-by-yields: true 
  save-extensions: ['pdf']

'h_ncleanjetspass_S3':
  log-y: true 
  sort-by-yields: true 
  save-extensions: ['pdf']

'h_ncleanjetspass_S4':
  log-y: true 
  sort-by-yields: true 
  save-extensions: ['pdf']

'h_ncleanjetspass_S5':
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf']

#b jet multiplicities
'h_ncleanbjetspass_notausf_S1':
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf']

'h_ncleanbjetspass_S2':
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf']

'h_ncleanbjetspass_S3':
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf']

'h_ncleanbjetspass_S4':
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf']

'h_ncleanbjetspass_S5':
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf']

#PV
'h_nvtx_notausf_S1':
  save-extensions: ['pdf']

'h_nvtx_S2':
  save-extensions: ['pdf']

'h_nvtx_S3':
  save-extensions: ['pdf']

'h_nvtx_S4':
  save-extensions: ['pdf']

'h_nvtx_S5':
  save-extensions: ['pdf']

#MET pt
'h_met_pt_notausf_S1':
  save-extensions: ['pdf']

'h_met_pt_S2':
  save-extensions: ['pdf']

'h_met_pt_S3':
  save-extensions: ['pdf']

'h_met_pt_S4':
  save-extensions: ['pdf']

'h_met_pt_S5':
  save-extensions: ['pdf']

#MET phi
'h_met_phi_notausf_S1':
  save-extensions: ['pdf']

'h_met_phi_S2':
  save-extensions: ['pdf']

'h_met_phi_S3':
  save-extensions: ['pdf']

'h_met_phi_S4':
  save-extensions: ['pdf']

'h_met_phi_S5':
  save-extensions: ['pdf']

#Muon pt
'h_muon1_pt_notausf_S1':
  save-extensions: ['pdf']

'h_muon1_pt_S2':
  save-extensions: ['pdf']

'h_muon1_pt_S3':
  save-extensions: ['pdf']

'h_muon1_pt_S4':
  save-extensions: ['pdf']

'h_muon1_pt_S5':
  save-extensions: ['pdf']

#Muon eta
'h_muon1_eta_notausf_S1':
  save-extensions: ['pdf']

'h_muon1_eta_S2':
  save-extensions: ['pdf']

'h_muon1_eta_S3':
  save-extensions: ['pdf']

'h_muon1_eta_S4':
  save-extensions: ['pdf']

'h_muon1_eta_S5':
  save-extensions: ['pdf']

#tau pt
'h_tau1_pt_S2':
  save-extensions: ['pdf']

'h_tau1_pt_S3':
  save-extensions: ['pdf']

'h_tau1_pt_S4':
  save-extensions: ['pdf']

'h_tau1_pt_S5':
  save-extensions: ['pdf']

#tau eta
'h_tau1_eta_S2':
  save-extensions: ['pdf']

'h_tau1_eta_S3':
  save-extensions: ['pdf']

'h_tau1_eta_S4':
  save-extensions: ['pdf']

'h_tau1_eta_S5':
  save-extensions: ['pdf']
