'h_ncleanjetspass_yield_S1':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  signal-normalize-data: false
  sort-by-yields: true 
  save-extensions: ['pdf']
  for-yields: true
  yields-table-order: 0
  yields-title: 'One muon'

'h_ncleanjetspass_yield_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  signal-normalize-data: false
  sort-by-yields: true 
  save-extensions: ['pdf']
  for-yields: true
  yields-table-order: 1
  yields-title: 'One tau'

'h_ncleanjetspass_yield_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  signal-normalize-data: false
  sort-by-yields: true 
  save-extensions: ['pdf']
  for-yields: true
  yields-table-order: 2
  yields-title: 'OS muon tau'

'h_ncleanjetspass_yield_S4':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  signal-normalize-data: false
  sort-by-yields: true 
  save-extensions: ['pdf']
  for-yields: true
  yields-table-order: 3
  yields-title: 'nJets\geq 3'

'h_ncleanjetspass_yield_S5':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  signal-normalize-data: false
  sort-by-yields: true
  save-extensions: ['pdf']
  for-yields: true
  yields-table-order: 4
  yields-title: 'One b-tagged jet'
