# nobweight     : pu + gen + lepton SF weights
# others        : pu + gen + lepton + btag SF weights
# S3
'hmuon1pt_nobweight_cut000':
  x-axis: "Muon p_{T} (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  ##log-y: true
  ##sort-by-yields: true
  y-axis-auto-range: true
  save-extensions: ['pdf']
'hmuon1eta_nobweight_cut000':
  x-axis: "Muon #eta"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  ##log-y: true
  ##sort-by-yields: true
  y-axis-auto-range: true
  save-extensions: ['pdf']
'htau1pt_nobweight_cut000':
  x-axis: "Tau p_{T} (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  ##log-y: true
  ##sort-by-yields: true
  y-axis-auto-range: true
  save-extensions: ['pdf']
'htau1eta_nobweight_cut000':
  x-axis: "Tau #eta"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  ##log-y: true
  ##sort-by-yields: true
  y-axis-auto-range: true
  save-extensions: ['pdf']
'hmuMETmt_nobweight_cut000':
  x-axis: "m_{T} (#mu#tau) (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  y-axis-auto-range: true
  save-extensions: ['pdf']
'hmutau_dR_nobweight_cut000':
  x-axis: "#Delta R (#mu#tau)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  y-axis-auto-range: true
  save-extensions: ['pdf']
'hmutau_mass_nobweight_cut000':
  x-axis: "m (#mu#tau) (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  y-axis-auto-range: true
  save-extensions: ['pdf']
'hncleanjetspass_nobweight_cut000':
  x-axis: "Number of Jets"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  y-axis-auto-range: true
  save-extensions: ['pdf']
# S4
'hncleanbjetspass_cut0000':
  x-axis: "Number of b-tagged Jets"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  y-axis-auto-range: true
  save-extensions: ['pdf']
'hjet1pt_nobweight_cut0000':
  x-axis: "Jet1 p_{T} (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  y-axis-auto-range: true
  save-extensions: ['pdf']
'hjet1eta_nobweight_cut0000':
  x-axis: "Jet1 #eta"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  y-axis-auto-range: true
  save-extensions: ['pdf']
'hjet2pt_nobweight_cut0000':
  x-axis: "Jet2 p_{T} (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  y-axis-auto-range: true
  save-extensions: ['pdf']
'hjet2eta_nobweight_cut0000':
  x-axis: "Jet2 #eta"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  y-axis-auto-range: true
  save-extensions: ['pdf']
'hjet3pt_nobweight_cut0000':
  x-axis: "Jet3 p_{T} (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  y-axis-auto-range: true
  save-extensions: ['pdf']
'hjet3eta_nobweight_cut0000':
  x-axis: "Jet3 #eta"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  y-axis-auto-range: true
  save-extensions: ['pdf']
'hmuon1pt_cut00000':
  x-axis: "Muon p_{T} (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  y-axis-auto-range: true
  save-extensions: ['pdf']
'hmuon1eta_cut00000':
  x-axis: "Muon #eta"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  #y-axis-auto-range: true
  y-axis-range: [0., 400.]
  save-extensions: ['pdf']
'htau1pt_cut00000':
  x-axis: "Tau p_{T} (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  y-axis-auto-range: true
  save-extensions: ['pdf']
'htau1eta_cut00000':
  x-axis: "Tau #eta"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  y-axis-auto-range: true
  y-axis-range: [0., 200.]
  save-extensions: ['pdf']
'hmutau_mass_cut00000':
  x-axis: "m (#mu#tau) (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  y-axis-auto-range: true
  save-extensions: ['pdf']
'hmutau_dR_cut00000':
  x-axis: "#Delta R (#mu#tau)"
  y-axis: "Events"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  y-axis-auto-range: true
  save-extensions: ['pdf']
'hmuMETmt_cut00000':
  x-axis: "m_{T} (GeV)"
  y-axis: "Events"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  y-axis-auto-range: true
  save-extensions: ['pdf']
'hmetpt_cut00000':
  x-axis: "MET (GeV)"
  y-axis: "Events"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  y-axis-auto-range: true
  save-extensions: ['pdf']
'hmetphi_cut00000':
  x-axis: "#phi of MET"
  y-axis: "Events"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  y-axis-auto-range: true
  save-extensions: ['pdf']
'hjet1pt_cut00000':
  x-axis: "Jet1 p_{T} (GeV)"
  y-axis: "Events"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  y-axis-auto-range: true
  save-extensions: ['pdf']
'hjet1eta_cut00000':
  x-axis: "Jet1 #eta"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  y-axis-auto-range: true
  y-axis-range: [0., 200.]
  save-extensions: ['pdf']
'hjet1btag_cut00000':
  x-axis: "Jet1 btag"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  y-axis-auto-range: true
  save-extensions: ['pdf']
'hjet2pt_cut00000':
  x-axis: "Jet1 p_{T} (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  y-axis-auto-range: true
  save-extensions: ['pdf']
'hjet2eta_cut00000':
  x-axis: "Jet2 #eta"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  y-axis-auto-range: true
  y-axis-range: [0., 200.]
  save-extensions: ['pdf']
'hjet2btag_cut00000':
  x-axis: "Jet2 btag"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  y-axis-auto-range: true
  save-extensions: ['pdf']
'hjet3pt_cut00000':
  x-axis: "Jet1 p_{T} (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  y-axis-auto-range: true
  save-extensions: ['pdf']
'hjet3eta_cut00000':
  x-axis: "Jet3 #eta"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  y-axis-auto-range: true
  y-axis-range: [0., 200.]
  save-extensions: ['pdf']
'hjet3btag_cut00000':
  x-axis: "Jet3 btag"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  y-axis-auto-range: true
  save-extensions: ['pdf']
'hbjet1pt_cut00000':
  x-axis: "bJet1 p_{T} (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  y-axis-auto-range: true
  save-extensions: ['pdf']
'hbjet1eta_cut00000':
  x-axis: "bJet1 #eta"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  y-axis-auto-range: true
  y-axis-range: [0., 200.]
  save-extensions: ['pdf']
'hchi2_SMTop_mass_cut00000':
  x-axis: "SM Top mass from #chi^{2} (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  y-axis-range: [0., 2000.]
  blinded-range: [0., 240.] 
  save-extensions: ['pdf']
'hchi2_SMW_mass_cut00000':
  x-axis: "SM W mass from #chi^{2} (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  y-axis-range: [0., 2000.]
  blinded-range: [0., 180.] 
  save-extensions: ['pdf']

