# h1  : pu + gen + lepton SF weights
# h   : pu + gen + lepton + btag SF weights
# S3
'h1muon1pt_cut000':
  x-axis: "Muon p_{T} (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  ##log-y: true
  ##sort-by-yields: true
  save-extensions: ['pdf']
'h1muon1eta_cut000':
  x-axis: "Muon #eta"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  ##log-y: true
  ##sort-by-yields: true
  save-extensions: ['pdf']
'h1tau1pt_cut000':
  x-axis: "Tau p_{T} (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  ##log-y: true
  ##sort-by-yields: true
  save-extensions: ['pdf']
'h1tau1eta_cut000':
  x-axis: "Tau #eta"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  ##log-y: true
  ##sort-by-yields: true
  save-extensions: ['pdf']
'h1muMETmt_cut000':
  x-axis: "m_{T} (#mu#tau) (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']
'h1mutau_dR_cut000':
  x-axis: "#Delta R (#mu#tau)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']
'h1mutau_mass_cut000':
  x-axis: "m (#mu#tau) (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']
'h1ncleanjetspass_cut000':
  x-axis: "Number of Jets"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']
# S4
'hncleanbjetspass_cut0000':
  x-axis: "Number of b-tagged Jets"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']
'h1jet1pt_cut0000':
  x-axis: "Jet1 p_{T} (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']
'h1jet1eta_cut0000':
  x-axis: "Jet1 #eta"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']
'h1jet2pt_cut0000':
  x-axis: "Jet2 p_{T} (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']
'h1jet2eta_cut0000':
  x-axis: "Jet2 #eta"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']
'h1jet3pt_cut0000':
  x-axis: "Jet3 p_{T} (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']
'h1jet3eta_cut0000':
  x-axis: "Jet3 #eta"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']
'hmuon1pt_cut00000':
  x-axis: "Muon p_{T} (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']
'hmuon1eta_cut00000':
  x-axis: "Muon #eta"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']
'htau1pt_cut00000':
  x-axis: "Tau p_{T} (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']
'htau1eta_cut00000':
  x-axis: "Tau #eta"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']
'hmutau_mass_cut00000':
  x-axis: "m (#mu#tau) (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']
'hmutau_dR_cut00000':
  x-axis: "#Delta R (#mu#tau)"
  y-axis: "Events"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']
'hmuMETmt_cut00000':
  x-axis: "m_{T} (GeV)"
  y-axis: "Events"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']
'hmetpt_cut00000':
  x-axis: "MET (GeV)"
  y-axis: "Events"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']
'hmetphi_cut00000':
  x-axis: "#phi of MET"
  y-axis: "Events"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']
'hjet1pt_cut00000':
  x-axis: "Jet1 p_{T} (GeV)"
  y-axis: "Events"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']
'hjet1eta_cut00000':
  x-axis: "Jet1 #eta"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']
'hjet1btag_cut00000':
  x-axis: "Jet1 btag"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']
'hjet2pt_cut00000':
  x-axis: "Jet1 p_{T} (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']
'hjet2eta_cut00000':
  x-axis: "Jet2 #eta"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']
'hjet2btag_cut00000':
  x-axis: "Jet2 btag"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']
'hjet3pt_cut00000':
  x-axis: "Jet1 p_{T} (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']
'hjet3eta_cut00000':
  x-axis: "Jet3 #eta"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']
'hjet3btag_cut00000':
  x-axis: "Jet3 btag"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']
'hbjet1pt_cut00000':
  x-axis: "bJet1 p_{T} (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']
'hbjet1eta_cut00000':
  x-axis: "bJet1 #eta"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  #log-y: true
  #sort-by-yields: true
  save-extensions: ['pdf']

# For example
#'h_DPhi_Ch2_S8':
#  y-axis: "Events"
#  y-axis-format: "%1% / %2$.2f"
#  save-extensions: ['pdf']
#  labels:
#  - {text: 'b4j4', position: [0.789, 0.806], size: 18}
