#  - ttLJ_xsec:   {type: const, value: 1.055, on: 'hist_TTpowhegttbb.root'}
#  - ttLL_xsec:   {type: const, value: 1.055, on: 'hist_TTLLpowhegttbb.root'}
#  - ttHad_xsec:  {type: const, value: 1.055, on: 'hist_TTHadpowhegttbb.root'}
##   - ttLJbb_xsec2:  {type: const, value: 1.17, on: 'hist_TTpowhegttbb.root'}
##   - ttLLbb_xsec2:  {type: const, value: 1.25, on: 'hist_TTLLpowhegttbb.root'}
##   - ttLJcc_xsec2:  {type: const, value: 1.5, on: 'hist_TTpowhegttcc.root'}
##   - ttLLcc_xsec2:  {type: const, value: 1.5, on: 'hist_TTLLpowhegttcc.root'}
#  - other_xsec1:   {type: const, value: 1.1, on: 'hist_DYJets.root'}
#  - other_xsec2:   {type: const, value: 1.1, on: 'hist_DYJets10to50.root'}
#  - other_xsec3:   {type: const, value: 1.1, on: 'hist_W1JetsToLNu.root'}
#  - other_xsec4:   {type: const, value: 1.1, on: 'hist_W2JetsToLNu.root'}
#  - other_xsec5:   {type: const, value: 1.1, on: 'hist_W3JetsToLNu.root'}
#  - other_xsec6:   {type: const, value: 1.1, on: 'hist_W4JetsToLNu.root'}
#  - other_xsec7:   {type: const, value: 1.1, on: 'hist_SingleTops.root'}
#  - other_xsec8:   {type: const, value: 1.1, on: 'hist_SingleTopt.root'}
#  - other_xsec9:   {type: const, value: 1.1, on: 'hist_SingleTbart.root'}
#  - other_xsec10:  {type: const, value: 1.1, on: 'hist_SingleToptW.root'}
#  - other_xsec11:  {type: const, value: 1.1, on: 'hist_SingleTbartW.root'}
#  - other_xsec12:  {type: const, value: 1.1, on: 'hist_WW.root'}
#  - other_xsec13:  {type: const, value: 1.1, on: 'hist_WZ.root'}
#  - other_xsec14:  {type: const, value: 1.1, on: 'hist_ZZ.root'}
#  - other_xsec15:  {type: const, value: 1.1, on: 'hist_ttHTobb.root'}
#  - other_xsec16:  {type: const, value: 1.1, on: 'hist_ttHToNonbb.root'}
#  - other_xsec17:  {type: const, value: 1.1, on: 'hist_TTWJetsToLNuPSweight.root'}
#  - other_xsec18:  {type: const, value: 1.1, on: 'hist_TTWJetsToQQ.root'}
#  - other_xsec19:  {type: const, value: 1.1, on: 'hist_TTZToLLNuNu.root'}
#  - other_xsec20:  {type: const, value: 1.1, on: 'hist_TTZToQQ.root'}
  - pu
  - jesAbsolute
  - jesAbsolute17
  - jesBBEC1
  - jesBBEC117
  - jesFlavorQCD
  - jesRelativeBal
  - jesRelativeSample17
  - btaghf
  - btaglf
  - btaghfstats1
  - btaglfstats1
  - btaghfstats2
  - btaglfstats2
  - btagcferr1
  - btagcferr2
#  - muid
#  - muiso
#  - mutrg
#  - elid
#  - elreco
#  - elzvtx
#  - eltrg
#  - jecAbsolute
#  - jecAbsolute2017
#  - jecBBEC1
#  - jecBBEC12017
#  - jecFlavorQCD
#  - jecRelativeBal
#  - jecRelativeSample2017
#  - jer
#  - scale: {type: shape, on: 'hist_TTpowhegttbb.root'}
#  - scale: {type: shape, on: 'hist_TTLLpowhegttbb.root'}
#  - scale: {type: shape, on: 'hist_TTHadpowhegttbb.root'}
#  - scale: {type: shape, on: 'hist_STTH1L3BHut.root'}
#  - scale: {type: shape, on: 'hist_STTH1L3BHct.root'}
#  - scale: {type: shape, on: 'hist_TTTH1L3BHut.root'}
#  - scale: {type: shape, on: 'hist_TTTH1L3BHct.root'}
#  - ps: {type: shape, on: 'hist_TTpowhegttbb.root'}
#  - ps: {type: shape, on: 'hist_TTLLpowhegttbb.root'}
#  - ps: {type: shape, on: 'hist_TTHadpowhegttbb.root'}
#  - ps: {type: shape, on: 'hist_STTH1L3BHut.root'}
#  - ps: {type: shape, on: 'hist_STTH1L3BHct.root'}
#  - ps: {type: shape, on: 'hist_TTTH1L3BHut.root'}
#  - ps: {type: shape, on: 'hist_TTTH1L3BHct.root'}
#  - hdamp: {type: shape, on: 'hist_TTpowhegttbb.root'}
#  - hdamp: {type: shape, on: 'hist_TTLLpowhegttbb.root'}
#  - hdamp: {type: shape, on: 'hist_TTHadpowhegttbb.root'}
#  - pdf: {type: shape, on: 'hist_TTpowhegttbb.root'}
#  - pdf: {type: shape, on: 'hist_TTLLpowhegttbb.root'}
#  - pdf: {type: shape, on: 'hist_TTHadpowhegttbb.root'}
#  - pdf: {type: shape, on: 'hist_STTH1L3BHut.root'}
#  - pdf: {type: shape, on: 'hist_STTH1L3BHct.root'}
#  - pdf: {type: shape, on: 'hist_TTTH1L3BHut.root'}
#  - pdf: {type: shape, on: 'hist_TTTH1L3BHct.root'}
#  - TuneCP5: {type: shape, on: 'hist_TTpowhegttbb.root'}
#  - TuneCP5: {type: shape, on: 'hist_TTLLpowhegttbb.root'}
#  - TuneCP5: {type: shape, on: 'hist_TTHadpowhegttbb.root'}
#  - lf
#  - hf
#  - lfstat1
#  - lfstat2
#  - hfstat1
#  - hfstat2
#  - cferr1
#  - cferr2
