  - ttLJ_xsec:   {type: const, value: 1.055, on: 'hist_TTToSemiLeptonic.root'}
  - ttLL_xsec:   {type: const, value: 1.055, on: 'hist_TTTo2L2Nu.root'}
  - ttHad_xsec:  {type: const, value: 1.055, on: 'hist_TTToHadronic.root'}
  - other_xsec1:  {type: const, value: 1.1, on: 'hist_DYJetsToLL_M10to50'}
  - other_xsec2:  {type: const, value: 1.1, on: 'hist_DYJetsToLL_M50_amc.root'}
  - other_xsec3:  {type: const, value: 1.1, on: 'hist_ST_s_4f_lepton.root'}
  - other_xsec4:  {type: const, value: 1.1, on: 'hist_ST_t_antitop_4f.root'}
  - other_xsec5:  {type: const, value: 1.1, on: 'hist_ST_t_top_4f.root'}
  - other_xsec6:  {type: const, value: 1.1, on: 'hist_ST_tW_antitop_5f.root'}
  - other_xsec7:  {type: const, value: 1.1, on: 'hist_ST_tW_top_5f.root'}
  - other_xsec8:  {type: const, value: 1.1, on: 'hist_ttHJetTobb.root'}
  - other_xsec9:  {type: const, value: 1.1, on: 'hist_ttHJetToNonbb.root'}
  - other_xsec10:  {type: const, value: 1.1, on: 'hist_TTWJetsToLNu.root'}
  - other_xsec11:  {type: const, value: 1.1, on: 'hist_TTWJetsToQQ.root'}
  - other_xsec12:  {type: const, value: 1.1, on: 'hist_TTZToLLNuNu.root'}
  - other_xsec13:  {type: const, value: 1.1, on: 'hist_TTZToQQ.root'}
  - other_xsec14:  {type: const, value: 1.1, on: 'hist_WJetsToLNu_HT0To100.root'}
  - other_xsec15:  {type: const, value: 1.1, on: 'hist_WJetsToLNu_HT100To200.root'}
  - other_xsec16:  {type: const, value: 1.1, on: 'hist_WJetsToLNu_HT200To400.root'}
  - other_xsec17:  {type: const, value: 1.1, on: 'hist_WJetsToLNu_HT400To600.root'}
  - other_xsec18:  {type: const, value: 1.1, on: 'hist_WJetsToLNu_HT600To800.root'}
  - other_xsec19:  {type: const, value: 1.1, on: 'hist_WJetsToLNu_HT800To1200.root'}
  - other_xsec20:  {type: const, value: 1.1, on: 'hist_WJetsToLNu_HT1200To2500.root'}
  - other_xsec21:  {type: const, value: 1.1, on: 'hist_WJetsToLNu_HT2500ToInf.root'}
  - other_xsec22:  {type: const, value: 1.1, on: 'hist_WW.root'}
  - other_xsec23:  {type: const, value: 1.1, on: 'hist_WZ.root'}
  - other_xsec24:  {type: const, value: 1.1, on: 'hist_ZZ.root'}
  - tes
  - jer
  - jesAbsolute
  - jesAbsolute_2018
  - jesBBEC1
  - jesBBEC1_2018
  - jesFlavorQCD
  - jesRelativeBal
  - jesRelativeSample_2018
  - btaghf
  - btaglf
  - btaghfstats1
  - btaglfstats1
  - btaghfstats2
  - btaglfstats2
  - btagcferr1
  - btagcferr2
  - pu
  - muid
  - muiso
  - mutrg
  - tauidjet
  - tauidmu
  - tauidel
#  - scale: {type: shape, on: 'hist_TTToSemiLeptonic.root'}
#  - scale: {type: shape, on: 'hist_TTTo2L2Nu.root'}
#  - scale: {type: shape, on: 'hist_TTToHadronic.root'}
#  - scale: {type: shape, on: 'hist_ST_LFV_TCMuTau_Scalar.root'}
#  - scale: {type: shape, on: 'hist_ST_LFV_TCMuTau_Vector.root'}
#  - scale: {type: shape, on: 'hist_ST_LFV_TCMuTau_Tensor.root'}
#  - scale: {type: shape, on: 'hist_ST_LFV_TUMuTau_Scalar.root'}
#  - scale: {type: shape, on: 'hist_ST_LFV_TUMuTau_Vector.root'}
#  - scale: {type: shape, on: 'hist_ST_LFV_TUMuTau_Tensor.root'}
#  - scale: {type: shape, on: 'hist_TT_LFV_TCMuTau_Scalar.root'}
#  - scale: {type: shape, on: 'hist_TT_LFV_TCMuTau_Vector.root'}
#  - scale: {type: shape, on: 'hist_TT_LFV_TCMuTau_Tensor.root'}
#  - scale: {type: shape, on: 'hist_TT_LFV_TUMuTau_Scalar.root'}
#  - scale: {type: shape, on: 'hist_TT_LFV_TUMuTau_Vector.root'}
#  - scale: {type: shape, on: 'hist_TT_LFV_TUMuTau_Tensor.root'}
#  - ps: {type: shape, on: 'hist_TTToSemiLeptonic.root'}
#  - ps: {type: shape, on: 'hist_TTTo2L2Nu.root'}
#  - ps: {type: shape, on: 'hist_TTToHadronic.root'}
#  - ps: {type: shape, on: 'hist_ST_LFV_TCMuTau_Scalar.root'}
#  - ps: {type: shape, on: 'hist_ST_LFV_TCMuTau_Vector.root'}
#  - ps: {type: shape, on: 'hist_ST_LFV_TCMuTau_Tensor.root'}
#  - ps: {type: shape, on: 'hist_ST_LFV_TUMuTau_Scalar.root'}
#  - ps: {type: shape, on: 'hist_ST_LFV_TUMuTau_Vector.root'}
#  - ps: {type: shape, on: 'hist_ST_LFV_TUMuTau_Tensor.root'}
#  - ps: {type: shape, on: 'hist_TT_LFV_TCMuTau_Scalar.root'}
#  - ps: {type: shape, on: 'hist_TT_LFV_TCMuTau_Vector.root'}
#  - ps: {type: shape, on: 'hist_TT_LFV_TCMuTau_Tensor.root'}
#  - ps: {type: shape, on: 'hist_TT_LFV_TUMuTau_Scalar.root'}
#  - ps: {type: shape, on: 'hist_TT_LFV_TUMuTau_Vector.root'}
#  - ps: {type: shape, on: 'hist_TT_LFV_TUMuTau_Tensor.root'}
#  - pdf: {type: shape, on: 'hist_TTToSemiLeptonic.root'}
#  - pdf: {type: shape, on: 'hist_TTTo2L2Nu.root'}
#  - pdf: {type: shape, on: 'hist_TTToHadronic.root'}
#  - pdf: {type: shape, on: 'hist_ST_LFV_TCMuTau_Scalar.root'}
#  - pdf: {type: shape, on: 'hist_ST_LFV_TCMuTau_Vector.root'}
#  - pdf: {type: shape, on: 'hist_ST_LFV_TCMuTau_Tensor.root'}
#  - pdf: {type: shape, on: 'hist_ST_LFV_TUMuTau_Scalar.root'}
#  - pdf: {type: shape, on: 'hist_ST_LFV_TUMuTau_Vector.root'}
#  - pdf: {type: shape, on: 'hist_ST_LFV_TUMuTau_Tensor.root'}
#  - pdf: {type: shape, on: 'hist_TT_LFV_TCMuTau_Scalar.root'}
#  - pdf: {type: shape, on: 'hist_TT_LFV_TCMuTau_Vector.root'}
#  - pdf: {type: shape, on: 'hist_TT_LFV_TCMuTau_Tensor.root'}
#  - pdf: {type: shape, on: 'hist_TT_LFV_TUMuTau_Scalar.root'}
#  - pdf: {type: shape, on: 'hist_TT_LFV_TUMuTau_Vector.root'}
#  - pdf: {type: shape, on: 'hist_TT_LFV_TUMuTau_Tensor.root'}
#  - hdamp: {type: shape, on: 'hist_TTToSemiLeptonic.root'}
#  - hdamp: {type: shape, on: 'hist_TTTo2L2Nu.root'}
#  - hdamp: {type: shape, on: 'hist_TTToHadronic.root'}
#  - py8tune: {type: shape, on: 'hist_TTToSemiLeptonic.root'}
#  - py8tune: {type: shape, on: 'hist_TTTo2L2Nu.root'}
#  - py8tune: {type: shape, on: 'hist_TTToHadronic.root'}
